### ISSUE TITLE
Installation within a theme

### ISSUE THREAD

**Issue by con322** [birgire/geo-query#1]
Hi just wondering if this can be installed within a theme is it as simple as just using require once in function with the path to geo-query.php?

Also when do a search is it as simple as? 

```
    'lat'                =>  $POST['current_location_lat'],                                // Latitude point
    'lng'                =>  $POST['current_location_lng'],                               // Longitude point
    'lat_meta_key'       =>  'my_lat',                          // Meta-key for the latitude data
    'lng_meta_key'       =>  'my_lng',                          // Meta-key for the longitude data 
    'radius'             =>  $POST['radius'], 
```

**Comment by birgire** [comment]
Hi @con322 

I haven't tested that but you should be able to do that, if I understand you correctly.

If you install the plugin and activate it, you should be able to use it in all your `WP_Query` calls where  you use the `geo_query` input argument. So you could also  use `pre_get_posts`  hook to modify main queries.

By default WP_Query supports `date_query`, `tax_query` and `meta_query`. So I was looking for a way to add support for a `geo_query` input argument, with this plugin.

Yes you could do the search as simple as that.

Hope that helps.
