### ISSUE TITLE
Retrieve distance information for an item

### ISSUE THREAD

**Issue by drawcard** [birgire/geo-query#18]
Hi, is there any way to retrieve information about the distance between two coordinates, eg "3.4 km" between Coordinate A & Coordinate B? It would be nice to display this to a user who is seeing results ordered by distance.

So far looking at the code, that value might be saved in [distance_value](https://github.com/birgire/geo-query/blob/master/src/GeoQueryHaversine.php#L105) but I think a function of some kind is required to extract it for display in a loop of items.

**Comment by birgire** [comment]
Hi @drawcard 

Have you tried e.g.:

```
$query = new WP_Query( $args );
while( $query->have_posts() ) {
	$query->the_post();
	echo get_post_field( 'distance_value' );
} 

```

**Comment by birgire** [comment]
Please reopen if needed
