### ISSUE TITLE
Structure query to search ACF Google Map fields in a Repeater field saved to a User

### ISSUE THREAD

**Issue by ghost** [birgire/geo-query#22]
Hi @birgire,

Can you please advise how the geo_query can be modified to search through an ACF (Advanced Custom Fields) Google Map field inside a Repeater field saved to a User?

I have found info how how to search through a field inside an ACF Repeater field (https://www.advancedcustomfields.com/resources/query-posts-custom-fields/) but I am unsure how to use it with geo_query.

Really appreciate your help

**Comment by birgire** [comment]
hi @futuretheory 

I wonder if a php function for distance calcs would be more useful to you instead of a sql method like this plugin uses.
