### ISSUE TITLE
wp-content/plugins/ directory is created when installing birgire/geo-query via Composer

### ISSUE THREAD

**Issue by wujekbogdan** [birgire/geo-query#5]
I'd like to use `geo-query` as a dependency for a plugin that I develop, but if `birgire/geo-query` is installed via Composer then `wp-content/plugins/` directory is created. Is it intentional? I would expect the dependency to be downloaded to the composer `vendor/geo-query` - this is a standard approach.

**Comment by birgire** [comment]
Hi @wujekbogdan 

Where is `wp-content/plugins` created in your case?

I wonder if it's because I've `"type":"wordpress-plugin"` in the` composer.json` ?

**Comment by wujekbogdan** [comment]
> Where is wp-content/plugins created in your case?

`wp-content/plugins` is created in the same directory where `composer install` command is executed.

```
├─── composer.json
├─── vendor
└─── wp-content
    └─── plugins
        └─── geo-query
```

> I wonder if it's because I've `"type":"wordpress-plugin"` in the `composer.json`?

You are probably right, this is a [composer/installers](https://github.com/composer/installers) feature.  [Here's an article](https://roots.io/wordpress-plugins-with-composer/) on this topic.

**Comment by birgire** [comment]
Thanks for the links.

I already require `composer/installers`, so maybe you could change the `installer-paths`, in the `extra `section, in your main ` composer.json` file? Something like:

```
{
    "extra": {
        "installer-paths": {
            "your/custom/path/{$name}/": ["birgir/geo-query"]
        }
    }
}

```

https://github.com/composer/installers
https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md

**Comment by wujekbogdan** [comment]
> I already require composer/installers

Yes, I know. But maybe you shouldn't use it? What's the benefit of using it? It looks like the installer causes that "issue".

Thanks for the `installer-path` tip. I'll use it as a workaround. But IMO it would be better if no additional effort was needed in order to install `birgir/geo_query` as a composer dependency.

**Comment by birgire** [comment]
I have now added `birgir/geo-query` as a package on packagist.com:

https://packagist.org/packages/birgir/geo-query

I just created a test plugin, that uses `birgir/geo-query` as a dependency.

The test plugin has the following `composer.json` file:

```
{
  "name": "birgir/test-plugin",
  "require": {
    "birgir/geo-query": "~0.0.5"
  },
  "extra": {
        "installer-paths": {
            "vendor/{$name}/": ["birgir/geo-query"]
        }
    }
}
```

This seems to work as expected and generates:

```
composer.json
composer.lock
vendor/
   autoload.php
   composer/
   birgir/
       geo-query/
```

instead of

```
composer.json
composer.lock
vendor/
   autoload.php
   composer/
wp-content/
    plugins/
        geo-query/
```

If I would not use the "wordpress-plugin" type and the `composer/installers`, what options would we have to install it to `wp-content/plugins` from a main site `composer.json`?

Maybe I should try and look for a WordPress plugin that is used both as a vendor library and a plugin, to see how it's usually done. (don't remember such a plugin at the moment)

ps: I'm just trying to understand the limitations and avoid "burning" any bridges ;-)

**Comment by wujekbogdan** [comment]
Thank you very much. I'll add an `extra` entry to my `composer.json` file for now. It's a workaround, but I can live with that :)

> If I would not use the "wordpress-plugin" type and the composer/installers, what options would we have to install it to wp-content/plugins from a main site composer.json?

Sadly I have no idea and I'm afraid I can't help you. I'm just a Composer user. I never made a composer public package.

You can try to have a look at [Timber](https://github.com/timber/timber) (a great tool by the way), they have a composer-compatible version and a WordPress plugin too.

**Comment by birgire** [comment]
great, thanks @wujekbogdan  I've heard about Timber but not used it. 

I will checkout Timber and try to learn how they do it.

I will mark this thread as resolved in the meanwhile ;-)

Thanks for the heads up, I learned from it ;-)
